spring.application.name=webstudyenglish
spring.datasource.url=jdbc:mysql://localhost:3306/ttcs
spring.datasource.username=root
spring.datasource.password=********
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate (JPA)
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

#thymeleaf
#cap nhat giao dien khong can chay lai app
spring.thymeleaf.cache=false 
#khai bao noi chua ui / cac trang thy
spring.thymeleaf.prefix=classpath:/templates/
# mac dinh se tim file .html
spring.thymeleaf.suffix=.html